version: '3.8'

services:
  # 1. db Container
  db:
    image: mysql:8.0
    container_name: climbingwith-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: climbingWith
    networks:
      - climbing-network
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
      interval: 5s

  # 2. Redisearch(VectorDB)
  vector:
    image: redis/redis-stack
    container_name: climbingwith-vectordb
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./vector_data:/data
    environment:
      - REDIS_ARGS=--save 60 1
    networks:
      - climbing-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # 3. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: climbingWith-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - climbing-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 4. spring boot app Container
  app:
    build: .
    container_name: climbingwith-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/climbingWith?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: p@ssword
    networks:
      - climbing-network
    depends_on:
      db:
        condition: service_healthy # DB의 healthcheck가 통과될 때까지 대기
      vector:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  climbing-network:
    driver: bridge